osx_image: xcode12.5
language: swift
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update
  - gem install cocoapods --pre
  - xcrun simctl list
install: echo "<3"
env:
  - MODE=build
  - MODE=examples
script: ./build.sh $MODE

# whitelist
branches:
  only:
    - master
