osx_image: xcode7.3
language: objective-c
sudo: required
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool
  - sudo gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - xcrun simctl list
  - which pod
  - pod --version
install: echo "<3"
env:
  - MODE=build
  - MODE=examples
script: ./build.sh $MODE

# whitelist
branches:
  only:
    - master
