source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

target 'Sample' do
  use_frameworks!

  # Pods for Sample
  #pod 'Localize-Swift', :path => '../..'
	
  pod 'Localize-Swift', :git => 'https://github.com/mariovillamizar/Localize-Swift.git', :commit => '554d61ff21dc0d7b14c63908cd70a00fd90d380d'

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
